version: '2'
services:
  # proxy:
  #   image: jwilder/nginx-proxy
  #   volumes:
  #     - ~/dev/web/wfeapp/proxy/logs/:/var/log/nginx/
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ~/dev/web/wfeapp/certs/server.crt:/etc/nginx/server.crt
  #     - ~/dev/web/wfeapp/certs/server.key:/etc/nginx/server.key
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   container_name: proxy
  #   restart: always
  nginx:
    build: ./nginx
    environment:
       TZ: Asia/Tokyo
       VIRTUAL_HOST: wfe.kasakaid.com
#       LETSENCRYPT_HOST: wfe.kasakaid1.tk
#       LETSENCRYPT_EMAIL: hoge@email.cohoge@email.com
    volumes:
      - ~/dev/web/wfeapp/nginx/logs/:/var/log/nginx/
      - ~/dev/web/wfeapp/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ~/dev/web/wfeapp/nginx/resources:/usr/share/nginx/html/
      - ~/dev/web/wfeapp/certs/server.crt:/etc/nginx/server.crt
      - ~/dev/web/wfeapp/certs/server.key:/etc/nginx/server.key
    hostname: wfe.kasakaid.com
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    labels:
      - "description=wfeサーバーです。"
      - "title=nginx"
    links:
      - tomcat:tomcat
    container_name: nginx #指定しない場合 compose_webserver_1 になる

  tomcat: 
    build: ./tomcat
    environment:
       TZ: Asia/Tokyo
       VIRTUAL_HOST: app.kasakaid.com
#       LETSENCRYPT_HOST: app.kasakaid1.tk
#       LETSENCRYPT_EMAIL: hoge@emailhoge.com
    hostname: app.kasakaid.com
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - ~/dev/java/springsecurity/build/libs/springsecurity-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/springsecurity.war
    labels:
      - "description=appサーバーです。"
      - "title=tomcat"
    container_name: tomcat
